// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjnIMayj02tLm5H40S7DihNuWiFiya7Bg',
    appId: '1:860161320958:web:50bd8ae07760c9c4fa42af',
    messagingSenderId: '860161320958',
    projectId: 'fomo-connect-469702',
    authDomain: 'fomo-connect-469702.firebaseapp.com',
    databaseURL: 'https://fomo-connect-469702-default-rtdb.firebaseio.com',
    storageBucket: 'fomo-connect-469702.firebasestorage.app',
    measurementId: 'G-SRPPKF1LSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCot2PqR0H4p7AFWmZJvNI36HKZX_apNo',
    appId: '1:860161320958:android:17d514ee13441dbffa42af',
    messagingSenderId: '860161320958',
    projectId: 'fomo-connect-469702',
    databaseURL: 'https://fomo-connect-469702-default-rtdb.firebaseio.com',
    storageBucket: 'fomo-connect-469702.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdubObvPPQa3XL4yRiRLA6sz4uDq58vTc',
    appId: '1:860161320958:ios:9c96ac6a51358063fa42af',
    messagingSenderId: '860161320958',
    projectId: 'fomo-connect-469702',
    databaseURL: 'https://fomo-connect-469702-default-rtdb.firebaseio.com',
    storageBucket: 'fomo-connect-469702.firebasestorage.app',
    iosClientId: '860161320958-vs32l7ivbjn8901vc4oigfkk3uqhfq9a.apps.googleusercontent.com',
    iosBundleId: 'com.terobytez.fomiiapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdubObvPPQa3XL4yRiRLA6sz4uDq58vTc',
    appId: '1:860161320958:ios:d0b1822b7132d61bfa42af',
    messagingSenderId: '860161320958',
    projectId: 'fomo-connect-469702',
    databaseURL: 'https://fomo-connect-469702-default-rtdb.firebaseio.com',
    storageBucket: 'fomo-connect-469702.firebasestorage.app',
    iosClientId: '860161320958-o0fa7if13g2pv0ik2s2olvs5ss0d06be.apps.googleusercontent.com',
    iosBundleId: 'com.example.fomoConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjnIMayj02tLm5H40S7DihNuWiFiya7Bg',
    appId: '1:860161320958:web:21cfaacd774b3565fa42af',
    messagingSenderId: '860161320958',
    projectId: 'fomo-connect-469702',
    authDomain: 'fomo-connect-469702.firebaseapp.com',
    databaseURL: 'https://fomo-connect-469702-default-rtdb.firebaseio.com',
    storageBucket: 'fomo-connect-469702.firebasestorage.app',
    measurementId: 'G-E0Z1KJCBV3',
  );

}