// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2aQtR9Zgmbw2_iM73dVMnpsXKbV-C_vQ',
    appId: '1:625047258752:web:489360b1330ed41e904865',
    messagingSenderId: '625047258752',
    projectId: 'fomo-connect',
    authDomain: 'fomo-connect.firebaseapp.com',
    storageBucket: 'fomo-connect.firebasestorage.app',
    measurementId: 'G-0C8Q8DV746',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU8jpM_NI4I2F1h1zEqXZzOro8bSfefHA',
    appId: '1:625047258752:android:c1d06f5a4239ee9c904865',
    messagingSenderId: '625047258752',
    projectId: 'fomo-connect',
    storageBucket: 'fomo-connect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3wMSQPFyrBd8H6frPEtsLXcR_Kv9lXTw',
    appId: '1:625047258752:ios:cea8588a9bc53895904865',
    messagingSenderId: '625047258752',
    projectId: 'fomo-connect',
    storageBucket: 'fomo-connect.firebasestorage.app',
    androidClientId: '625047258752-hk1nqdrtvmq0v2l60qrdnip66m4t3s13.apps.googleusercontent.com',
    iosClientId: '625047258752-6mjod1ecqibk1m2oll4lec57a5vot7td.apps.googleusercontent.com',
    iosBundleId: 'com.example.fomoConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3wMSQPFyrBd8H6frPEtsLXcR_Kv9lXTw',
    appId: '1:625047258752:ios:cea8588a9bc53895904865',
    messagingSenderId: '625047258752',
    projectId: 'fomo-connect',
    storageBucket: 'fomo-connect.firebasestorage.app',
    androidClientId: '625047258752-hk1nqdrtvmq0v2l60qrdnip66m4t3s13.apps.googleusercontent.com',
    iosClientId: '625047258752-6mjod1ecqibk1m2oll4lec57a5vot7td.apps.googleusercontent.com',
    iosBundleId: 'com.example.fomoConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2aQtR9Zgmbw2_iM73dVMnpsXKbV-C_vQ',
    appId: '1:625047258752:web:6dc607217a0a9ce8904865',
    messagingSenderId: '625047258752',
    projectId: 'fomo-connect',
    authDomain: 'fomo-connect.firebaseapp.com',
    storageBucket: 'fomo-connect.firebasestorage.app',
    measurementId: 'G-P7YCXVS5XD',
  );

}